In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Shopee pip pip calon mantu/order_brush_order.csv')

In [ ]:
df.head()

orderid     shopid     userid           event_time
0  31076582227611   93950878   30530270  2019-12-27 00:23:03
1  31118059853484  156423439   46057927  2019-12-27 11:54:20
2  31123355095755  173699291   67341739  2019-12-27 13:22:35
3  31122059872723   63674025  149380322  2019-12-27 13:01:00
4  31117075665123  127249066  149493217  2019-12-27 11:37:55

In [ ]:
df.describe()

orderid        shopid        userid
count  2.227500e+05  2.227500e+05  2.227500e+05
mean   3.130027e+13  9.433117e+07  9.802880e+07
std    1.222774e+11  5.695790e+07  6.839048e+07
min    3.107520e+13  1.000900e+04  1.000700e+04
25%    3.120360e+13  4.980267e+07  3.508127e+07
50%    3.130561e+13  9.033636e+07  9.309625e+07
75%    3.140604e+13  1.475053e+08  1.590612e+08
max    3.150720e+13  2.154352e+08  2.155262e+08

In [ ]:
#buat ngubah string to date time
df["event_time"] = pd.to_datetime(df['event_time'])

In [ ]:
#Get all orders with group by userid and shopid
df = df.set_index(pd.DatetimeIndex(df['event_time'])).drop('event_time', axis=1).sort_index()
orders = df.groupby(['shopid', 'userid', pd.Grouper(freq='H',label='left', base=0)]).count()
#nah freq='H' itu buat nampilin jam kalo freq='M' yab=ng muncul tahun doang

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: 'base' in .resample() and in Grouper() is deprecated.
The new arguments that you should use are 'offset' or 'origin'.

>>> df.resample(freq="3s", base=2)

becomes:

>>> df.resample(freq="3s", offset="2s")

  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
orders

orderid
shopid    userid    event_time                  
10009     196962305 2019-12-27 03:00:00        1
10051     2854032   2019-12-27 19:00:00        1
          48600461  2019-12-29 01:00:00        1
10061     62464559  2019-12-31 02:00:00        1
          130633421 2019-12-30 21:00:00        1
...                                          ...
214949521 46269178  2019-12-31 20:00:00        1
214964814 200983383 2019-12-29 22:00:00        1
215175775 13688804  2019-12-31 09:00:00        1
          129266028 2019-12-31 14:00:00        1
215435223 79515106  2019-12-31 18:00:00        1

[215877 rows x 1 columns]

In [ ]:
brush_order = orders[orders.orderid >=3]
brush_order
#ini aku ambil data order id >=3

orderid
shopid    userid    event_time                  
10159     214988798 2019-12-29 20:00:00        3
10287     198097381 2019-12-30 00:00:00        3
          214226569 2019-12-31 01:00:00        3
10402     77819     2019-12-28 14:00:00        3
10536     672345    2019-12-27 11:00:00        3
...                                          ...
203531250 114282846 2019-12-29 17:00:00        3
204225676 198662175 2019-12-31 00:00:00        5
208696908 214111334 2019-12-30 17:00:00        3
210197928 52867898  2019-12-27 07:00:00        4
213141071 213646699 2019-12-27 01:00:00        3

[742 rows x 1 columns]

In [ ]:
listuserid = []
brush_order.reset_index().groupby('shopid')['userid'].apply(lambda x: listuserid.append(x.values))

shopid
10159        None
10287        None
10402        None
10536        None
29583        None
             ... 
203531250    None
204225676    None
208696908    None
210197928    None
213141071    None
Name: userid, Length: 296, dtype: object

In [ ]:
listuserid

[array([214988798]),
 array([198097381, 214226569]),
 array([77819]),
 array([672345, 672345]),
 array([214495220, 215275495]),
 array([740844]),
 array([170385453]),
 array([190449497]),
 array([214992524]),
 array([264511]),
 array([181682008]),
 array([7670129]),
 array([75558350, 75558350]),
 array([62618064]),
 array([141006168]),
 array([565381]),
 array([188942105]),
 array([181408876]),
 array([15053804]),
 array([ 78451300, 123959597]),
 array([214568881]),
 array([212325226]),
 array([143847348]),
 array([740844]),
 array([556867]),
 array([9753706]),
 array([ 13135622, 162508227, 215382704]),
 array([197569856]),
 array([148176353]),
 array([84811421]),
 array([210920501]),
 array([8405753]),
 array([95058664]),
 array([148215831]),
 array([214546342]),
 array([136680607]),
 array([148215831]),
 array([156614746]),
 array([214588488]),
 array([128838735]),
 array([195918606]),
 array([32594]),
 array([128702876]),
 array([200925208]),
 array([205729485, 205729485, 205729485]

In [ ]:
brush_order.reset_index().drop_duplicates(subset = ["shopid"])
#drop duplicate shopide

shopid     userid          event_time  orderid
0        10159  214988798 2019-12-29 20:00:00        3
1        10287  198097381 2019-12-30 00:00:00        3
3        10402      77819 2019-12-28 14:00:00        3
4        10536     672345 2019-12-27 11:00:00        3
6        29583  214495220 2019-12-27 23:00:00        4
..         ...        ...                 ...      ...
737  203531250  114282846 2019-12-29 17:00:00        3
738  204225676  198662175 2019-12-31 00:00:00        5
739  208696908  214111334 2019-12-30 17:00:00        3
740  210197928   52867898 2019-12-27 07:00:00        4
741  213141071  213646699 2019-12-27 01:00:00        3

[296 rows x 4 columns]

In [ ]:
#concat userid
def concat_userid(data):
    result = '&'.join(str(x) for x in data)
    return result

bulk_userid = []
for i in listuserid:
    bulk_userid.append(concat_userid(i))

In [ ]:
bulk_userid

['214988798',
 '198097381&214226569',
 '77819',
 '672345&672345',
 '214495220&215275495',
 '740844',
 '170385453',
 '190449497',
 '214992524',
 '264511',
 '181682008',
 '7670129',
 '75558350&75558350',
 '62618064',
 '141006168',
 '565381',
 '188942105',
 '181408876',
 '15053804',
 '78451300&123959597',
 '214568881',
 '212325226',
 '143847348',
 '740844',
 '556867',
 '9753706',
 '13135622&162508227&215382704',
 '197569856',
 '148176353',
 '84811421',
 '210920501',
 '8405753',
 '95058664',
 '148215831',
 '214546342',
 '136680607',
 '148215831',
 '156614746',
 '214588488',
 '128838735',
 '195918606',
 '32594',
 '128702876',
 '200925208',
 '205729485&205729485&205729485',
 '214300427',
 '93880473',
 '192684666',
 '102125116',
 '115994773',
 '107170776',
 '154495684',
 '4163235',
 '89014205',
 '192400689',
 '2824209',
 '193338089',
 '213989374',
 '170673735',
 '19037973',
 '135952',
 '9069878&128431789',
 '188025647',
 '88991923',
 '174145893',
 '192785138',
 '114498557',
 '33794624',
 '158

In [ ]:
df_brush = pd.DataFrame({"shopid": brush_order.reset_index()['shopid'].unique(), "userid": bulk_userid})
df_brush.head()

shopid               userid
0   10159            214988798
1   10287  198097381&214226569
2   10402                77819
3   10536        672345&672345
4   29583  214495220&215275495

Setelah dianalisa terdapat 5 shopee id dan 8 user id yang terindikasi melakukan order burshing (pesanan palsu) dengan melakukan pemesanan berulang